#!/bin/bash

# Set build dir
export BUILD_DIR=$HOME/build_dir
mkdir -p $BUILD_DIR

# Install chealpix
wget https://sourceforge.net/projects/healpix/files/Healpix_3.11/autotools_packages/chealpix-3.11.4.tar.gz && \
    tar xzf chealpix-3.11.4.tar.gz && \
    cd chealpix-3.11.4 && \
    ./configure --enable-shared --prefix=$BUILD_DIR && \
    make && \
    make install && \
    cd

# Install libsharp
git clone https://github.com/Libsharp/libsharp.git $HOME/software/libsharp && \
    cd $HOME/software/libsharp && \
    autoconf -i && \
    ./configure --enable-pic && \
    make && \
    cd

# Install GSL
wget https://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz --passive-ftp -P $HOME/software && \
    cd $HOME/software && \
    tar -xzf gsl-2.5.tar.gz && \ 
    cd gsl-2.5 && \
    ./configure --enable-shared --prefix=$BUILD_DIR && \
    make && \
    make install && \
    cd

# Clone NaMaster from github
git clone https://github.com/LSSTDESC/NaMaster $HOME/software/NaMaster

# Set flags
export PATH=$HOME/software/libsharp/auto/bin:$BUILD_DIR:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BUILD_DIR:$HOME/software/libsharp/auto/lib:/usr/local/lib
export LDFLAGS="-L$BUILD_DIR/lib -L$HOME/software/libsharp/auto/lib -L/usr/local/lib"
export CPPFLAGS="-I$BUILD_DIR/include -I$HOME/software/libsharp/auto/include -I/usr/local/include -fopenmp"
export CFLAGS="-I$BUILD_DIR/include -I$HOME/software/libsharp/auto/include -fopenmp"
export CPPFLAGS="-I$BUILD_DIR/include -I$HOME/software/libsharp/auto/include -I/usr/local/include -fopenmp"

# Install NaMaster C libraries
cd $HOME/software/NaMaster/ && \
    ./configure --prefix=$BUILD_DIR && \
    make && \
    make install && \
    make check

# Install NaMaster Python wrapper
cd $HOME/software/NaMaster && \
    python setup.py install && \
    python -m unittest discover -v
