#!/bin/bash

# Set build dir
export BUILD_DIR=$HOME/build_dir
mkdir -p $BUILD_DIR

# Install CIBinfo with pip
pip install git+git://github.com/DanielLenz/CIBinfo.git

# Install chealpix
wget https://sourceforge.net/projects/healpix/files/Healpix_3.11/autotools_packages/chealpix-3.11.4.tar.gz && \
    tar xzf chealpix-3.11.4.tar.gz && \
    cd chealpix-3.11.4 && \
    ./configure --enable-shared --prefix=$BUILD_DIR && \
    make && \
    make install && \
    cd

# Install libsharp
git clone https://github.com/Libsharp/libsharp.git $HOME/software/libsharp && \
    cd $HOME/software/libsharp && \
    autoconf -i && \
    ./configure --enable-pic && \
    make && \
    cd

# Install GSL
wget https://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz --passive-ftp -P $HOME/software && \
    cd $HOME/software && \
    tar -xzf gsl-2.5.tar.gz && \ 
    cd gsl-2.5 && \
    ./configure --enable-shared --prefix=$BUILD_DIR && \
    make && \
    make install && \
    cd

# Clone NaMaster from github
git clone https://github.com/LSSTDESC/NaMaster $HOME/software/NaMaster

# Sets envs and compiler flags
source $HOME/.envs.sh

# Ensure that this is also run in the .bashrc
echo "source \$HOME/.envs.sh" >> $HOME/.bashrc

# Install NaMaster C libraries
cd $HOME/software/NaMaster/ && \
    ./configure --enable-shared --prefix=$BUILD_DIR && \
    make && \
    make install && \
    make check

# Install NaMaster Python wrapper
cd $HOME/software/NaMaster && \
    python setup.py install && \
    python -m unittest discover -v
